# Define firmware version
export PRJ_VERSION = 0x00000001

# Define target output
target: dcp

# Define target part
export PRJ_PART = XCZU15EG-FFVB1156-1-E

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
